WIP: wireshark add
davestephens/ansible-nas pull request #578
Opened 2022-08-16 22:03 UTC by bcurran3

**What this PR does / why we need it**:

**Which issue (if any) this PR fixes**:

Fixes #

**Any other useful info**:

2022-08-17 06:34 UTC, davestephens requested changes

2022-08-17 06:34 UTC, davestephens commented on roles/wireshark/defaults/main.yml
> +wireshark_port: "3000"   # host mode - for reference only
Can remove this one

2022-08-17 15:41 UTC, bcurran3 commented on roles/wireshark/defaults/main.yml
> +wireshark_port: "3000"   # host mode - for reference only
done

2022-08-18 07:26 UTC, davestephens approved these changes

2022-08-18 07:27 UTC, davestephens approved these changes

2022-08-18 07:29 UTC, merged

2022-08-18 07:29 UTC, davestephens commented
Awesome addition! 👍