Added code-server app
davestephens/ansible-nas pull request #596
Opened 2022-08-21 20:12 UTC by HitLuca

Added code-server image, which is VSCode server without the Microsoft branding. Also it is open source, I prefer to add this instead of VSCode honestly.

Still a work in progress, we are missing docs and app ports sections for code-server, the rest is there and has been tested.

It also adds a `code_root` variable, which is where the projects would be stored. I chose it to be `samba_shares_root/code`

**Which issue (if any) this PR fixes**:

Fixes #534

**Any other useful info**:
I noticed that since code-server has a PUID/PGID of 0, all files created are owned by root. Changing the ids to, for example, the ones of `ansible_nas_user` would be better in my opinion

2022-08-21 22:00 UTC, HitLuca commented
I just remembered one thing: it's better to have the choice of using code-server and vscode-server, since the open source code-server doesn't have all the extensions available in the marketplace.

If it's ok for you I can make another pr for vscode-server tomorrow

2022-08-23 00:02 UTC, davestephens requested changes

2022-08-23 08:45 UTC, HitLuca commented
Before it was vscode-server, when I refactored the name I forgot to reorder it lol

2022-08-23 09:51 UTC, HitLuca commented
> I just remembered one thing: it's better to have the choice of using code-server and vscode-server, since the open source code-server doesn't have all the extensions available in the marketplace.

Well forget what I said, I was thinking of `Codium`, which is VSCode without branding, not `code-server` vs `vscode-server` my bad. There's no `vscode-server` docker image, only `code-server`, which is VSCode containerized. More details [here](https://www.roboleary.net/tools/2022/05/31/vscode-vscodium-which-should-i-use.html)

I'll just add docs for this and the PR is good to go

2022-08-23 21:59 UTC, davestephens approved these changes

2022-08-23 22:00 UTC, merged