Add Apcupsd role
davestephens/ansible-nas pull request #625
Opened 2022-12-17 10:01 UTC by codemeister64

**What this PR does / why we need it**:
Adds Apcupsd role - tool that allows to retrieve info from connected APC UPS and gracefully shutdown host machine in case of power outage

**Which issue (if any) this PR fixes**:
-
Fixes #

**Any other useful info**:
-

2022-12-17 11:13 UTC, davestephens requested changes
This looks cool! Please can you fix the linting issues then we should be good to go 👍

2022-12-17 21:16 UTC, codemeister64 commented
Hey davestephens! 
Thanks for the quick review. I've fixed linting issues. However, one CI job still failing, about `yarn.lock`, but I'm not sure, that it should be resolved in scope of this PR. Could you please take a look?

2023-01-04 14:41 UTC, codemeister64 commented
Hey @davestephens! 
How it is going? Would you please double-check (and probably merge?) this PR?
Thank in advance!

2024-02-17 19:42 UTC, codemeister64 commented
Hi @davestephens! Could you please re-review PR when you get a chance. All linting issues are fixed. Thanks in advance!

2024-10-09 20:28 UTC, davestephens approved these changes

2024-10-09 20:29 UTC, merged

2024-10-09 20:30 UTC, davestephens commented
Thank you! Apologies for the obscenely long time this took to get merged....