Paperless ngx
davestephens/ansible-nas pull request #652
Opened 2023-02-19 00:30 UTC by viktor-c

I hereby request to add paperless_ngx to the list of apps, since paperless_ng has not been developed for a while and it's original repo has been archived. 
I based the files on hello_world example and used the paperless_ngx official example [docker-compose file](https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.postgres-tika.yml)

This [PR](https://github.com/davestephens/ansible-nas/pull/651) which is just a couple of hours younger as mine does not integrate tests. 

Since I am a hobby developer I could not get tests working, appreciate some help in that direction: python venv and vagrant are working; `test.sh` output is blank, `github-test-matrix.sh` outputs `::set-output name=matrix::[""]`

2023-02-19 01:21 UTC, viktor-c commented
Fixed some linting errors
Setting paperless_ngx_enabled to true and then to false should trigger stopping all containers, but these tasks always get skipped in ansible ? Any idea why?

2023-02-19 14:32 UTC, viktor-c commented
As of now, testing the role also works.

2023-02-19 21:13 UTC, viktor-c commented
>  Setting paperless_ngx_enabled to true and then to false should trigger stopping all containers, but these tasks always get skipped in ansible ? Any idea why?

fixed that with above [commit](https://github.com/davestephens/ansible-nas/pull/652/commits/f1517976bca69ec1cec91f20fab922ebc630f56e)

2023-04-01 20:13 UTC, viktor-c commented
Ran [CI](https://github.com/viktor-c/ansible-nas/actions/workflows/ci.yml) and [Integration](https://github.com/viktor-c/ansible-nas/actions/runs/4584935470/jobs/8096758269) (only passing for paperless-ngx).

Don't know why the other roles don't pass molecule tests, could be something to do with: https://github.com/davestephens/ansible-nas/pull/655#issue-1620010041 which fixes the tests.

2023-04-16 09:55 UTC, viktor-c commented
[![Integration](https://github.com/viktor-c/ansible-nas/actions/workflows/integration.yml/badge.svg?branch=paperless_ngx)](https://github.com/viktor-c/ansible-nas/actions/workflows/integration.yml)

Thanks to last Pullrequest (as of 16.04.2023) CI passes all tests.

2023-05-07 07:26 UTC, tanc requested changes
Works well except for a mismatch on the container names within the network for gotenberg and tika making then inaccessible within the network from paperless.

2023-05-07 07:26 UTC, tanc commented on roles/paperless_ngx/defaults/main.yml
> +paperless_tika_gotenberg_name: "gotenberg"
Should be the same as `paperless_ng_container_name_gotenberg` value, e.g. `paperless_ng_gotenberg`

2023-05-07 07:26 UTC, tanc commented on roles/paperless_ngx/defaults/main.yml
> +paperless_tika_name: "tika"
Should be the same as `paperless_ng_container_name_tika` value, e.g. `paperless_ng_tika`

2023-05-07 07:27 UTC, tanc commented on roles/paperless_ngx/defaults/main.yml
Or just `paperless_xxx`

2024-11-20 10:16 UTC, closed without merging