:sparkles: Add badge with role count
davestephens/ansible-nas pull request #654
Opened 2023-03-06 09:56 UTC by anarion80

**What this PR does / why we need it**:

Adds a badge that shows the number of roles/applications. It counts the number of directories in `roles` directory. The count is approximate (we have 3 internal roles), but still it's nice ;)

**Which issue (if any) this PR fixes**:

Fixes #

**Any other useful info**:

2023-04-09 19:46 UTC, davestephens commented
This is a really neat idea! Please move it to the very top of the readme though, ie, the first badge, and rename it "Available Applications", and add the `flat-square` style to match the other badges.

2023-04-09 19:47 UTC, davestephens requested changes
Please change per the PR comment :+1:

2023-04-10 08:49 UTC, anarion80 commented
Updated as per PR comment

2023-04-10 10:50 UTC, davestephens approved these changes

2023-04-10 10:50 UTC, merged