💥 Update ALL remaining roles to new format (with docs and tests)
davestephens/ansible-nas pull request #655
Opened 2023-03-11 13:50 UTC by anarion80

**What this PR does / why we need it**:

As in the title: I updated all the remaining roles to new format - adding docs and molecule tests. I know this doesn't really adhere to your contributing guideline, but you're probably busy, PR intake is slow, so here it is.

While creating passing tests I had to fix some roles:
- Krusader had old, non-existent image
- Nomad needed gpg key update
- Timemachine needed apt cache update
- Wallabag needed additional directories created with certain permissions (can be a bug in Wallabag currently)
- ZNC needed a starting config file as it was interactive and thus not easy to automate testing for

From the general things:
- Fixed lint
- Moved from deprecated links to networks for certain roles
- Added variables for container image names:versions instead of hardcoding in tasks
- Updated Ansible module names to use fully qualified collection name (FQCN)

All passing tests are here: https://github.com/anarion80/ansible-nas/actions/runs/4392401003

**Which issue (if any) this PR fixes**:

Fixes #

**Any other useful info**:

2023-03-13 00:03 UTC, davestephens commented
Wow, this is amazing, thank you!

I'll start reviewing this week, hopefully won't take too long to get merged.

2023-03-16 23:20 UTC, davestephens requested changes
This looks great, thank you for taking the time!

Few comments;

- all of the doc moves have been dragged and dropped rather than `git mv ....`, which means the files are showing as new additions, and we lose the history.
- the roles I'd already rejigged are missing the new docker settings - these are a nice addition so would be good to add
- the docs generation doesn't currently cater for docs within the role directories, so will need some shell scripting to set up (or the docs be left in their original location for now).

2023-03-16 23:20 UTC, davestephens commented on roles/znc/templates/znc.conf.j2
Why is this file changing?

2023-03-17 08:13 UTC, anarion80 commented on roles/znc/templates/znc.conf.j2
Without the config, ZNC container is restarting:

```
Checking for list of available modules... 
Opening config [/znc-data/configs/znc.conf]... [ No such file ]
Restart ZNC with the --makeconf option if you wish to create this config.
Unrecoverable config error.
```

expecting a run with --makeconf.

Restarting container is not good for automated checking in test, I figured updating tasks to deal with interactive config is also not really the best way to go - hence the ready-made config.

2023-03-17 08:15 UTC, anarion80 commented on roles/emby/molecule/default/verify.yml
I think it was already there: https://github.com/davestephens/ansible-nas/blob/master/roles/emby/molecule/default/verify_stopped.yml

2023-03-17 08:25 UTC, anarion80 commented on roles/nomad/molecule/default/verify.yml
> +          - service_result.status['ActiveState'] == "active"
Yes, I think so:

```
"name": "nomad",
    "state": "started",
    "status": {
        "ActiveEnterTimestamp": "Fri 2023-03-17 08:20:51 UTC",
        "ActiveEnterTimestampMonotonic": "998571988",
        "ActiveExitTimestamp": "Fri 2023-03-17 08:20:51 UTC",
        "ActiveExitTimestampMonotonic": "998544668",
        "ActiveState": "active",
        ...
        "Result": "success",
        ....
```

But you're probably right that this:
```
- name: Get Nomad service state
      ansible.builtin.systemd:
        name: nomad
        state: started
```

should be rather:
```
- name: Get Nomad service state
      ansible.builtin.systemd:
        name: "{{ nomad_service_name }}"
        state: started
```

2023-03-17 09:17 UTC, anarion80 commented
> all of the doc moves have been dragged and dropped rather than git mv ...., which means the files are showing as new additions, and we lose the history.

Do you mean moves of existing docs from `website` into roles? If so - yes, I can remove then, do `git mv ...` and update if necessary.

> the roles I'd already rejigged are missing the new docker settings - these are a nice addition so would be good to add

Which setting do you mean exactly?

> the docs generation doesn't currently cater for docs within the role directories, so will need some shell scripting to set up (or the docs be left in their original location for now)

Yes, so the docs are left in their original settings (when I add new roles for myself I add docs to both locations for now), and in new roles location - just to be consistent with `hello_world` example and ready for any future script updates.

2023-03-28 15:34 UTC, anarion80 commented
Well, I copying the files using git-cp which was supposed to copy git history, but I don't see that git history :/

2023-04-09 19:37 UTC, davestephens commented
> Well, I copied the files using git-cp which was supposed to copy git history, but I don't see that git history :/

Ah, that makes sense why they are showing as new files. I think it'll end up as a management nightmare having two copies of the docs - so please can we remove the new copies and leave the docs where they were originally. Once I get to sorting out the docs generation I can move them into the roles again!

2023-04-10 08:44 UTC, anarion80 commented
Ok, I removed the new/individual docs, and also rebased to upstream

2023-04-18 21:55 UTC, merged

2023-04-18 21:57 UTC, davestephens commented
Finally got this one merged - thanks for your efforts - I also did a fair bit of extra work on it :)

Also - the following tests aren't passing:

```
FAILED roles/joomla/molecule/default/molecule.yml::test
FAILED roles/nextcloud/molecule/default/molecule.yml::test
FAILED roles/openhab/molecule/default/molecule.yml::test
FAILED roles/piwigo/molecule/default/molecule.yml::test
FAILED roles/transmission-with-openvpn/molecule/default/molecule.yml::test
FAILED roles/virtual_desktop/molecule/default/molecule.yml::test
```

It seems that they are all roles that have been flipped to creating a network over the legacy `link` method. Did you see this in testing?

2023-04-19 06:21 UTC, anarion80 commented
Thanks! Yes, I fillpped them over to the new method over deprecated link method.
I quickly checked the first two roles on `new_format` branch and they are passing tests all right.
I will rebase my master and check there.

2023-04-19 09:11 UTC, davestephens commented
Interestingly they pass on GitHub, but fail locally. I'll do some more
digging!

On Wed, 19 Apr 2023, 07:22 Anarion, ***@***.***> wrote:

> Thanks! Yes, I fillpped them over to the new method over deprecated link
> method.
> I quickly checked the first two roles on new_format branch and they are
> passing tests all right.
> I will rebase my master and check there.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/davestephens/ansible-nas/pull/655#issuecomment-1514191513>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFDGMEC4RGGB2VZS4TFGXDXB6AAXANCNFSM6AAAAAAVXP5TF4>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>