Add homepage descriptions and entries for Bazarr, Piwigo, PyLoad, and YoutubeDL Material
davestephens/ansible-nas pull request #717
Opened 2024-06-15 14:40 UTC by darshitpp

**What this PR does / why we need it**:
I noticed that some of the services that I used, did not list themselves on `Homepage`. Adding the same.

2024-06-18 21:24 UTC, davestephens requested changes
Nearly there, just a minor tweak needed :)

2024-06-18 21:24 UTC, davestephens commented on roles/piwigo/tasks/main.yml
> +          homepage.href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:80"
Please replace 80 with `{{ piwigo_port}}`

2024-06-19 14:45 UTC, darshitpp commented on roles/piwigo/tasks/main.yml
> +          homepage.href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:80"
Fixed

2024-06-19 16:59 UTC, merged

2024-06-19 16:59 UTC, davestephens commented
Awesome, thanks!